### PR TITLE
13498288 google referer restrictions

### PR DESCRIPTION
**Pull request by damonsharp**
This fixes an issue where restricting Google Calendar API referers when creating an API key would cause calendar display to break. This fix adds `referer` headers to the Google Client [here](https://github.com/sureswiftcapital/Simple-Calendar/compare/master...13498288-google-referer-restrictions?expand=1#diff-95bb045948343939383803deac3d8218R142).

Ref: [Trello](https://trello.com/c/BMRh7LQt) / [Teamwork](https://codivated.teamwork.com/#tasks/13498288)

This also updates `npm` dependencies as well as bumps the composer Google Client library from v1.x to v2.x.

These changes should be thoroughly tested for compatibility, including with all internal add-ons (Fullcalendar, Simple Calendar Pro, etc.). Most breaking client library changes pertaining to v1 -> v2 upgrade relate to items beyond just reading the Google Calendar feed data, so impact here shouldn't be an issue. I tested myself, but would like another set of eyes. More info [here](https://github.com/googleapis/google-api-php-client/blob/master/UPGRADING.md).

**Testing scenarios:**

Since this fix if for issues with API referer restrictions, in order to test, an API key must first be restricted via Google Console [here](https://console.developers.google.com/apis/credentials?project={your_project}). For example if testing on https://codivated.com/calendar for example, restrict specifically to that url or use wildcards such as in this screenshot...

Screen Shot 2019-03-19 at 9 24 01 PM

Keep in mind that after setting the restriction it can take a few minutes before it becomes active. Once that is set and active, test the following using both Google Calendar free as well as with the Pro & FullCalendar addons...

1. Can you create a calendar without issue?
1. Embedding the calendar in a page or post works correctly.
1. Try a variety of settings... this includes grid, list, fullcalendar, pro, free, grouped calendars, etc.
     1. do they all work? If not, what combination(s) do not work, and what errors do you see?
1. Try a variety of events? Adding and removing new events in Google works okay and shows up on the WP end okay (once calendar cache is cleared -- event changes won't show unless this is done).

Reply with a comment below if you have questions.

### CODE REVIEW

**Comment by zachwills** [comment]
@damonsharp code LGTM, can you outline some testing instructions that we can have someone run through to verify things are working as they should? I'm a bit nervous with all the dependency updates that something minor may break.

**Comment by damonsharp** [comment]
@zachwills Sure. I'll document items tonight.

**Comment by damonsharp** [comment]
@zachwills there are so many numerous combinations of settings that I can't really touch on everything that should be tested, but mainly anything that pertains to the connection between the plugin and the API, i.e. adding and deleting events on Google's end syncs up correctly, any url restrictions that don't work, etc. API error messages will only show on the front end when logged in (as and admin i think). Just have whomever hit me up with any questions if needed.

**Comment by damonsharp** [comment]
@zachwills any feedback on this one? i know you were reaching out to Jim for someone to put this through its paces.

**Pull request merged**
