### PR TITLE
Fix to close #341 - allow this plugin to co-exist with others that use the google api client

### LINKED ISSUE #341: The plugin is incompatible with other Google-using plugins
Hi,
I am the author of the [Image and video gallery from Google Drive](https://wordpress.org/plugins/skaut-google-drive-gallery/) plugin. I just wanted to let you know that your plugin is unfortunately incompatible with other plugins using the Google API. You include the Google API files (parts of your vendor folder basically), however, you leave all the files "un-prefixed". If any other plugin does so, it breaks because of double-defining classes.

I found this out because of a clash with our plugin (that is also caused by a mistake on our side, which should be fixable). A way out of this mess is to put all of your vendor code into a custom namespace so that there is no clash if multiple instances of one dependency are included. To see how we did it, you can look [here](https://github.com/skaut/skaut-google-drive-gallery/blob/master/gulpfile.js#L36-L299) (However, I think we are a bit too aggressive with pruning unused code, which leads to a slightly brittle implementation)

### PR DESCRIPTION
**Pull request by mickwall001**
This will break the premium add on's as they will need to pull in the new name spaced dependencies.

### CODE REVIEW

**Comment by nickyoung87** [comment]
@mickwall001 Thank you for contributing this. I am going to look this over.

**Comment by nickyoung87** [comment]
This is really cool and I like the use of `php-scoper`. I have never heard of it or used it before, but I like this a lot more than the way I was going to implement this. I am, however, running into a slight issue with the script. It gives me an error when it tries to add all to the output. 

`'php-scoper' is not recognized as an internal or external command, operable program or batch file.`

It's interesting because I can directly run that line in my command line, but through the script doing it automatically I keep getting that issue. I am trying to find a way around that, but I figured I would share here in case you had any experience with that particular problem.

**Comment by mickwall001** [comment]
Hi Nick

 

Thanks, I had all sorts of issues because the box I used is a sinology NAS box that’s not really great at doing this!

 

I assume the php-scoper/vendor/bin/php-scoper has been pulled dowb by composer?  The script deletes this after running sop maybe remove that rm -v line and see if it all looks OK?

 

Its weird composer will run though so must be an environment thing somewhere!

 

My output from that section looks like this

 

 

Using version 1.0.x-dev for humbug/php-scoper

./composer.json has been updated

Running composer update humbug/php-scoper

Loading composer repositories with package information

Updating dependencies

Lock file operations: 13 installs, 0 updates, 0 removals

  - Locking composer/package-versions-deprecated (dev-master f921205)

  - Locking humbug/php-scoper (dev-master a0e7de3)

  - Locking jetbrains/phpstorm-stubs (dev-master 89eb456)

  - Locking nikic/php-parser (v4.10.4)

  - Locking psr/container (dev-master 381524e)

  - Locking symfony/console (4.4.x-dev 1a9570e)

  - Locking symfony/filesystem (4.4.x-dev 83a6fee)

  - Locking symfony/finder (4.4.x-dev 64aa7b2)

  - Locking symfony/polyfill-ctype (dev-main c6c942b)

  - Locking symfony/polyfill-mbstring (dev-main f377a3d)

  - Locking symfony/polyfill-php73 (dev-main a678b42)

  - Locking symfony/polyfill-php80 (dev-main dc3063b)

  - Locking symfony/service-contracts (dev-main bf99754)

Writing lock file

Installing dependencies from lock file (including require-dev)

Package operations: 13 installs, 0 updates, 0 removals

  - Syncing composer/package-versions-deprecated (dev-master f921205) into cache

  - Syncing symfony/finder (4.4.x-dev 64aa7b2) into cache

  - Syncing symfony/polyfill-ctype (dev-main c6c942b) into cache

  - Syncing symfony/filesystem (4.4.x-dev 83a6fee) into cache

  - Syncing psr/container (dev-master 381524e) into cache

  - Syncing symfony/service-contracts (dev-main bf99754) into cache

  - Syncing symfony/polyfill-php80 (dev-main dc3063b) into cache

  - Syncing symfony/polyfill-php73 (dev-main a678b42) into cache

  - Syncing symfony/polyfill-mbstring (dev-main f377a3d) into cache

  - Syncing symfony/console (4.4.x-dev 1a9570e) into cache

As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.

This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.

Installing 'unzip' may remediate them.

  - Syncing jetbrains/phpstorm-stubs (dev-master 89eb456) into cache

  - Syncing humbug/php-scoper (dev-master a0e7de3) into cache

  - Installing composer/package-versions-deprecated (dev-master f921205): Cloning f921205948 from cache

  - Installing symfony/finder (4.4.x-dev 64aa7b2): Cloning 64aa7b2541 from cache

  - Installing symfony/polyfill-ctype (dev-main c6c942b): Cloning c6c942b1ac from cache

  - Installing symfony/filesystem (4.4.x-dev 83a6fee): Cloning 83a6feed14 from cache

  - Installing psr/container (dev-master 381524e): Cloning 381524e856 from cache

  - Installing symfony/service-contracts (dev-main bf99754): Cloning bf99754c61 from cache

  - Installing symfony/polyfill-php80 (dev-main dc3063b): Cloning dc3063ba22 from cache

  - Installing symfony/polyfill-php73 (dev-main a678b42): Cloning a678b42e92 from cache

  - Installing symfony/polyfill-mbstring (dev-main f377a3d): Cloning f377a3dd1f from cache

  - Installing symfony/console (4.4.x-dev 1a9570e): Cloning 1a9570e565 from cache

  - Installing nikic/php-parser (v4.10.4): Extracting archive

  - Installing jetbrains/phpstorm-stubs (dev-master 89eb456): Cloning 89eb456a21 from cache

  - Installing humbug/php-scoper (dev-master a0e7de3): Cloning a0e7de3ac9 from cache

5 package suggestions were added by new dependencies, use `composer suggest` to see details.

Generating autoload files

composer/package-versions-deprecated: Generating version class...

composer/package-versions-deprecated: ...done generating version class

10 packages you are using are looking for funding.

Use the `composer fund` command to find out more!

> php-scoper/vendor/bin/php-scoper add --output-dir=./third-party –force

 

Hope you get it sorted – its all new to me so have been a lot of trial and error!  Let me know if you want me to send the add-ons code over as they will be required.

 

Cheers

 

Mick

**Comment by mickwall001** [comment]
Nick, try changing the php-scoper line to

 "./php-scoper/vendor/bin/php-scoper add --output-dir=./third-party --force",
 
 I realised I had a php-scoper in my path that was being picked up!

**Comment by nickyoung87** [comment]
Yeah I tried that also, still no go for me. I can run the actual command so I am thinking it must have something to do with the folder being dynamically created. Everything else is working so great though. If I can just test it and get it working then I am sure we can push this out into a new release.

**Comment by mickwall001** [comment]
OK Nick

Not sure what to suggest now, seems odd you can run it from the command line but the script is failing.  Remember the premium add ons will need an update at the same time.

**Comment by nickyoung87** [comment]
No problem I am going to keep debugging it. I really appreciate your contribution here and I will do whatever I can to get it integrated!

**Comment by mickwall001** [comment]
Hi Nick.  What flavour of Unix are you using.  I'll try and spin up a VM on google to see if I can help any further.

**Comment by mickwall001** [comment]
OK, so I just spun up a new VM on Azure, installed php 7.3 and composer, ran composer update and it all just worked. so your issue is confusing

**Comment by nickyoung87** [comment]
Hey Mick,

So I am using WIndows. I think that might be part of the problem here. I am using bash to run the commands and that works fine, but maybe when the script runs it doesn't have the same permissions or something weird...who knows when it comes to Windows. 

I am going to see if I can try to do this on a Linux installation via ssh on my local machine. Hopefully that will work and if it does then I can at least have it narrowed down to a Windows issue. I will keep you updated when I have more info.

**Comment by mickwall001** [comment]
Ok thanks.  I never even thought of running it on Windows 😥I am. It sure pho-scoper will run from a quick browse of the forums!

Hope you have some luck - apart from this seems to run Ok!

**Comment by nickyoung87** [comment]
Yes this looks so great and promising. I just need to be able to do the full build in order to update the plugin, that is my main concern. 

I am seeing now they have a way to implement it via PHP which may be worth checking out too. 

Again, really appreciate your work on this!

**Comment by kalich5** [comment]
Mainly to reduce the size of the plugin. And there were no unnecessary pieces of code.

**Comment by nickyoung87** [comment]
@mickwall001 Which includes file is this line trying to go to?

`cd includes && echo '{ \"autoload\": { \"classmap\": [\"\"] } }' > composer.json && composer dump-autoload --classmap-authoritative --no-interaction  && rm composer.json`

**Comment by mickwall001** [comment]
That was just dumping the auto load after pho scoper had run as far as I could work out.   I am new to PHP and auto load so it’s all a bit of a mystery!

Regards

Mick
________________________________

**Comment by nickyoung87** [comment]
Awesome, thank you!

**Comment by nickyoung87** [comment]
@mickwall001 So I have made some great progress towards getting this to work I think. basically, what I am doing is trying to convert what you have in the composer post-install script into a separate bash script that can just be run. This allows me to actually run php-scoper successfully (I also added it to my path).

Here is a gist of the bash file I have created: https://gist.github.com/nickyoung87/f9653eaeefcc53c0669bd2d42190cdec

So with that I am actually able to start progressing through the process more since it is not giving me an error for php-scoper not being a recognized command. Now though, I am back to wondering why we are changing to the includes folder to create a composer.json file. I get that we are just doing that to be able to dump the autoload right? But couldn't we just run `composer dump-autoload` as a command?

I am curious your thoughts here and insight since you have more familiarity with php-scoper than I do. Below are the screenshots of my last attempt at running this script.

image

image

**Comment by mickwall001** [comment]
You need to be running php-scoper from the root on the app - not from the php-scoper directory, that maybe the issue?

**Comment by nickyoung87** [comment]
Yeah I actually was just noticing that was happening. I wonder why it switches into that directory. Let me do everything from the root and see what happens.

**Comment by nickyoung87** [comment]
Oh ok so the second line of the script has a `cd php-scoper`...is that meant to be there? Seems like we should be doing that all from root as well?

**Comment by mickwall001** [comment]
I think the composer.json I created, the prefix-dependencies section it must return to the root after each command, I think each line effectively spawns a new command environment - you will have to mimic that in the bash file

I would also say that the developer of php-scoper says it may not work under windows so lets see, it was looking good till that error - its parsing the same number of files that I see.

**Comment by nickyoung87** [comment]
Hopefully that isn't the case. It still feels really promising at this point to me. So to clarify you are saying it should be more like this?

```rm -rf php-scoper && mkdir php-scoper
cd php-scoper && composer init -q --name "calendar/php_scoper" --stability dev && composer require humbug/php-scoper
php-scoper add --output-dir=./third-party --force
cd ../
cd includes && echo "{ \"autoload\": { \"classmap\": [\"\"] } }" > composer.json && composer dump-autoload --classmap-authoritative --no-interaction  && rm composer.json
cd ../
cd third-party && echo "{ \"autoload\": { \"classmap\": [\"\"],\"files\":[\"guzzlehttp/psr7/src/functions_include.php\"] } }" > composer.json && composer dump-autoload --classmap-authoritative --no-interaction && rm composer.json
cd ../```

**Comment by mickwall001** [comment]
I guess, does that run?

**Comment by nickyoung87** [comment]
It does, but it's not 100% accurate. I am using `pwd` to try and get a trace ow what is going on. Seems I get moved to the wrong directory somewhere else in the line.

**Comment by nickyoung87** [comment]
What is the directory tree supposed to look like in relation to the plugin folder?

MAIN PLUGIN FOLDER
- php-scoper
- third-party

Those 2 folders should be in the same as the base folder, correct?
And then when we are copying from the vendor folder it should be going from where to where.

Maybe if you could help me see what the structure is supposed to look like then I can better understand how to manipulate the bash script.

I want to take a moment to again just thank you for your work here! :)

**Comment by mickwall001** [comment]
Here is my root structure


root@Micks-vm:/usr/share/wordpress/wp-content/plugins/google-calendar-events# ls -lrt
total 348
drwxr-xr-x  6 www-data www-data   4096 Feb 11 21:54 assets
-rw-r--r--  1 www-data www-data 175424 Feb 11 21:54 package-lock.json
drwxr-xr-x  2 www-data www-data   4096 Feb 11 21:54 i18n
-rw-r--r--  1 root     root        215 Feb 11 22:33 bower.json
-rw-r--r--  1 root     root       5159 Feb 11 22:33 gruntfile.js
-rw-r--r--  1 root     root       3283 Feb 11 22:33 contributing.md
-rw-r--r--  1 root     root       3747 Feb 11 22:33 scoper.inc.php
-rw-r--r--  1 www-data www-data  31733 Feb 11 22:33 readme.txt
-rw-r--r--  1 root     root       1487 Feb 11 22:33 readme.md
-rw-r--r--  1 root     root        745 Feb 11 22:33 package.json
-rw-r--r--  1 www-data www-data  18091 Feb 11 22:33 license.txt
-rw-r--r--  1 www-data www-data   1488 Feb 11 22:33 uninstall.php
-rw-r--r--  1 root     root       2528 Feb 11 22:34 composer.json
-rw-r--r--  1 www-data www-data   1684 Feb 11 22:36 google-calendar-events.php
-rw-r--r--  1 root     root      62324 Feb 13 22:06 composer.lock
drwxr-xr-x 16 root     root       4096 Feb 13 23:05 vendor
drwxr-xr-x 11 www-data www-data   4096 Feb 13 23:05 includes
drwxr-xr-x 12 root     root       4096 Feb 13 23:05 third-party
root@Micks-vm:/usr/share/wordpress/wp-content/plugins/google-calendar-events#

**Comment by nickyoung87** [comment]
Oh interesting. And where is the php-scoper folder being added before it's removed? I thought it was supposed to be in root, but looks like you have some that are up a level inside `www-data`?

**Comment by nickyoung87** [comment]
I think in either case if we can get this running as a bash script that would be better and more likely to run on different machines. If it is a little hacky right now I don't even really mind as long as I can get it to run and complete then I can make the proper updates to the pro plugins and push this thing live to the WP repo. But until I can get this script running I won'e be able to do that.

**Comment by mickwall001** [comment]
php-scoper is created at that top level, its not there because as you say its deleted after.

www-data is just the owner of the directory

here it is when not removed...


drwxr-xr-x  6 www-data www-data   4096 Feb 11 21:54 assets
-rw-r--r--  1 www-data www-data 175424 Feb 11 21:54 package-lock.json
drwxr-xr-x  2 www-data www-data   4096 Feb 11 21:54 i18n
-rw-r--r--  1 www-data www-data    215 Feb 11 22:33 bower.json
-rw-r--r--  1 www-data www-data   5159 Feb 11 22:33 gruntfile.js
-rw-r--r--  1 www-data www-data   3283 Feb 11 22:33 contributing.md
-rw-r--r--  1 www-data www-data   3747 Feb 11 22:33 scoper.inc.php
-rw-r--r--  1 www-data www-data  31733 Feb 11 22:33 readme.txt
-rw-r--r--  1 www-data www-data   1487 Feb 11 22:33 readme.md
-rw-r--r--  1 www-data www-data    745 Feb 11 22:33 package.json
-rw-r--r--  1 www-data www-data  18091 Feb 11 22:33 license.txt
-rw-r--r--  1 www-data www-data   1488 Feb 11 22:33 uninstall.php
-rw-r--r--  1 www-data www-data   1684 Feb 11 22:36 google-calendar-events.php
-rw-r--r--  1 www-data www-data  62324 Feb 13 22:06 composer.lock
drwxr-xr-x 16 www-data www-data   4096 Feb 13 23:05 vendor
-rw-r--r--  1 www-data www-data   2504 Feb 14 20:10 composer.json
drwxr-xr-x  3 www-data www-data   4096 Feb 14 20:10 php-scoper
drwxr-xr-x 11 www-data www-data   4096 Feb 14 20:10 includes

**Comment by nickyoung87** [comment]
Ah ok I see.

SO yeah it looks like php-scoper and third-party should be at the same level. 

Thanks, I will keep playing with this!

**Comment by mickwall001** [comment]
Yes, everything comes off the root, when you ship the plugin you need to ship the third-party and NOT the vendor as its not used

**Comment by nickyoung87** [comment]
That makes sense. We are just copying everything from vendor, re-namespacing it, and then adding those to the third-party folder. THen the third-party folder will be the path to use the files instead of vendor. Cool that makes a lot of sense.

**Comment by mickwall001** [comment]
Nick, in the script this may work.  For each line of commands do

bash -c "rm -rf php-scoper && mkdir php-scoper"
etc

I think this will create a new bash environment and run the commands then return to the original bash environment

So your script may look something like

bash -c "cd php-scoper && composer init -q --name \"calendar/php_scoper\" --stability dev && composer require humbug/php-scoper"
bash -c "php-scoper add --output-dir=./third-party --force"
bash -c "includes && echo \"{ \"autoload\": { \"classmap\": [\"\"] } }/" > composer.json && composer dump-autoload --classmap-authoritative --no-interaction  && rm composer.json"
bash -c "cd third-party && echo \"{ \"autoload\": { \"classmap\": [\"\"],\"files\":[\"guzzlehttp/psr7/src/functions_include.php\"] } }\" > composer.json && composer dump-autoload --classmap-authoritative --no-interaction && rm composer.json"


i don't have the same environment as you so save your current work!

**Comment by mickwall001** [comment]
[calendar bash script.txt](https://github.com/sureswiftcapital/Simple-Calendar/files/5978473/calendar.bash.script.txt)

cus and paste has lots all the escaping!, I attached an example

**Comment by mickwall001** [comment]
[calendar bash script.txt](https://github.com/sureswiftcapital/Simple-Calendar/files/5978746/calendar.bash.script.txt)

OK here is a version of the script that works on my system - I had to break a couple of line apart as I couldn;t make the escaping work!

Let me know how you get on

**Comment by mickwall001** [comment]
I've pushed those changes up - lets hope it helps

**Comment by nickyoung87** [comment]
Thank you so much @mickwall001 I will test this out as soon as I get the chance!

**Comment by mickwall001** [comment]
How's it going @nickyoung87, any luck with that script?

**Comment by nickyoung87** [comment]
Working on it today, so I will keep you posted. Thanks!

**Comment by nickyoung87** [comment]
I had to make some small adjustments, but it looks like it actually has completed running the bash script. Now it's just fixing some issues with the classes causing fatal errors, but it looks like this is on the right track now!

**Comment by mickwall001** [comment]
Ok. Good news.   If it all works
Properly the basic plugin should not need anything else going to it.  

As I was developing it I kept running in to issues and started playing with the base classes but in the end it was all in the scoper inc file that got it fixed.  (Apart from changing all the references to calls to google classes where I removed the leading \

Hope you manage to get it
Sorted.  As it happened I know longer use this as we
Moved to Microsoft 365! And my add on licence has now expired.  

Happy to help get this over the line

Mick

**Comment by nickyoung87** [comment]
Thnks Mick. Your dive into this has been super helpful.

Do you get a message about there not being a lock file when you run this?

**Comment by mickwall001** [comment]
Hi Nick.  No I don’t get any errors

Regards

Mick
________________________________

**Comment by mickwall001** [comment]
@nickyoung87 if you can describe your build environment I'll try to re-create it and see what's happening.  I am not convinced pho-scoper will run the same but would need to check.  I've created a Ubuntu VM on my Windows machine using the built in hypervisor in windows 10 pro and that works great so could that be an option?

**Comment by nickyoung87** [comment]
I am just running windows 10 home edition. Using git bash to run the command line stuff. I don't know what hypervisor is, but you did just give me a thought that maybe if I run it in some VM box that I can copy the final build out of then that would at least work for now.

**Comment by mickwall001** [comment]
OK Nick, the HyperVisor allows you to run a UNIX machine right on your windows 10 machine but you do need windows 10 pro.

A little more info here

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

So what webserver do you run the wordpress site / plugin on (apache?) can you tell me which download you used - just so I can have it the same,

**Comment by nickyoung87** [comment]
Well I have the WP set up through Local by Flywheel for this specific test site. I do have WampServer available as well, but I don't think that will really make a difference. THe main issue I am getting is just trying to run the shell stuff. I think I am getting errors now because PHP scoper isn't running 100% accurately.

**Comment by mickwall001** [comment]
Hi @nickyoung87 I have managed to create a windows environment and found the issues.  I've just pushed another fix up.  The issues you were having were due to windows using \ in directories and unix using /.  This caused 2 issues, firstly the build issues and secondly to do with the php-scoper patching process.

I managed to code the scoper.inc.php to cope with both I think but I couldn't work out how to do it with the composer.json, so for now there is a composer.json.win and a composer.json.unix, just copy the one you want as composer.json before running composer.

Let me know how that goes for you

**Comment by mickwall001** [comment]
OK, I've managed to find a way to have a single composer file that will work on Windows or Unix.

**Comment by mickwall001** [comment]
@nickyoung87  -spent most of the day trying to get this sorted - I've built on windows and then copied it to my plugins area on UNIX and it  seems to be working.  Let me know how you get on,.

**Comment by mickwall001** [comment]
Hi @nickyoung87 had any luck with this?

**Comment by nickyoung87** [comment]
@mickwall001 Hey sorry I have been quite busy. I am looking at this now. I didn't realize you had gone and done all of that, thank you!

**Comment by nickyoung87** [comment]
Unfortunately it still looks like there is an issue for me. Maybe I need to just switch to linux 😂 

image

**Comment by mickwall001** [comment]
OK, I don't het that, I can build it from a native windows command prompt as well as the windows git/bash shell.  I assume there is a lockfile? and the permissions are all OK?

**Comment by nickyoung87** [comment]
I believe so. I don't know the permissions stuff. Do I need to try running in something like powershell as administrator?

image

**Comment by mickwall001** [comment]
can you show contents of the includes?

**Comment by nickyoung87** [comment]
image

**Comment by mickwall001** [comment]
looks the same as mine - struggling now!

**Comment by nickyoung87** [comment]
Weirdly it's kind of comforting to know at least that they look the same. I wonder if it's something to do with the path. Do you have php-scoper or any of the commands directly tied into your PATH? Maybe I need to add/remove something from there.

**Comment by mickwall001** [comment]
Composer is in the path but nothing else.  Do you have any composer plug-ins installed? That's the only google reference I can see.

**Comment by nickyoung87** [comment]
hmm I might have something installed. I'm not really sure. I can take a look into that.

**Comment by nickyoung87** [comment]
Well I checked my PATH, I have a ton of stuff there, but I noticed I had added php-scoper there so I thought removing it might help. Removed it and it still fails. Also tried running it as an admin and still no luck. Gonna keep trying to find every little possible thing that I can. 

Just wanna say again, I appreciate your work on this so much.

**Comment by mickwall001** [comment]
What version of composer are you using?   Is it up to date.  Try composer self-update and see why it does.  


Also I assume you have a composer.bat file? Can you post what that looks like?   We are so close, just a couple of commands away!  The complex stuff is done!


May also be worth running those lines manually and see what happens - I think you can run composer in verbose mode to give a stack trace something like composer -vvv the the rest of the command.  

As it's 'working on my machine' it's hard to help much more, I had never heard of composer before doing this! So I don't have much knowledge.

**Comment by nickyoung87** [comment]
Good question, I had not thought about checking compser version. I will do that now. I know we are so close. Unfortunately, I am much better at writing code than all of this windows vs unix stuff haha. But we re almost there. I will check composer now.

**Comment by mickwall001** [comment]
Here is my version

C:\Users\mick_1dz1wpr\Documents\GitHub\Simple-Calendar>composer --version
Composer version 2.0.11 2021-02-24 14:57:23

it may also be worth doing 

composer clearcache

that gives

C:\Users\mick_1dz1wpr\Documents\GitHub\Simple-Calendar>composer clearcache
Clearing cache (cache-vcs-dir): C:\Users\mick_1dz1wpr\AppData\Local\Composer\vcs
Clearing cache (cache-repo-dir): C:\Users\mick_1dz1wpr\AppData\Local\Composer\repo
Clearing cache (cache-files-dir): C:\Users\mick_1dz1wpr\AppData\Local\Composer\files
Clearing cache (cache-dir): C:\Users\mick_1dz1wpr\AppData\Local\Composer
All caches cleared.



here is my output from a buld - standard windows command box

image

**Comment by nickyoung87** [comment]
So my composer version is the same `2.0.11`. I tried the clearcache hoping that might help, but still no go.

I did have some luck with a previous iteration trying to run each command one at a time, so I need to still try and do that and see what happens.

**Comment by mickwall001** [comment]
OK Nick, sorry for the trouble - I am officially out of ideas!

**Comment by nickyoung87** [comment]
Please don't be sorry! You're help here has been tremendous. I still think it's right on the cusp of being resolved. So I will keep kicking around ideas on my side to see if I can get it working. It's gotta just be something to do with my setup. Hopefully running each command on it's own will just do the trick and we can put this to rest. Again, very grateful and appreciative of your work here.

**Comment by mickwall001** [comment]
@nickyoung87. ok, I've updated composer.json to use --no-plugins and -vvv so can you give it a go and see, please put the output here if it still fails as we should get more information.

**Comment by nickyoung87** [comment]
I just ran this. It doesn't appear like I got any error messages this time. I will have to install the plugin and check that it works this evening or tomorrow. I will let you know how that goes, but looks real promising now!

**Comment by mickwall001** [comment]
Good news, remember the pro addons wont work.  I do have the changes needed if you want them

**Comment by nickyoung87** [comment]
So far this is looking really solid now. I have a fatal error dealing with Carbon. Looking through the PHP scoper I don't see it in there (or I am blind). Did you exclude it purposefully?

**Comment by nickyoung87** [comment]
Oh I see it now, I forgot it was nesbot. Disregard my question.

**Comment by mickwall001** [comment]
Ok. So you have it all working

**Comment by nickyoung87** [comment]
Yep it looks like it! Thank you SO SO MUCH for this. Is it ok if I use your github name in our changelog for your fantastic work on this?

**Comment by mickwall001** [comment]
Yes that is fine, thanks. don't forget it breaks the pro addons!

**Comment by nickyoung87** [comment]
Thanks, that's what I am working on next!

**Comment by mickwall001** [comment]
OK, I can send you my changes if you tell be how you want them

**Comment by nickyoung87** [comment]
Oh sure you can send it to nickyoungweb@gmail.com if you would like.

**Pull request merged**
